export const ADD_ANALOGY_RESULT = 'ADD_ANALOGY_RESULT';
export const ADD_ASL_OUTPUT_TEXT = 'ADD_ASL_OUTPUT_TEXT';
export const ADD_ENGLISH_INPUT_TEXT = 'ADD_ENGLISH_INPUT_TEXT';
export const ADD_ANALOGY_INPUT = 'ADD_ANALOGY_INPUT';